---
galaxy_info:
  author: Richard M. Williams
  role_name: ansible-role-compliance-windows-security-options-policy-2012
  description: Win2012 Check & Remediation for the CIS Security Options section.
  company: IBM Corp
  license: IBM Intellectual Property
  min_ansible_version: 1.8
  platforms:
    - name: Windows
      versions:
        - 2012 and higher
  galaxy_tags:
    - system
    - server
    - windows
    - compliance
dependencies: []
